### ISSUE TITLE
无法在Firefox中在线构建

### ISSUE THREAD

**Issue by RainStar7981** [Teahouse-Studios/mcwzh-meme-web-builder-react#30]
**注意：这里是Web Builder的仓库，如果和资源包内容有关，强烈建议您前往 https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack 进行反馈。**

## 简述错误
无法使用Firefox在线构建，提示”在向服务器请求资源模块列表时发生了错误。“，新版和旧版均有此问题

## 重现方法
使用Firefox浏览器打开在线构建网站。

## 提交截图
新版：
![图片](https://user-images.githubusercontent.com/94267417/175866093-fde01328-e5c6-49c0-9558-3c6c8e956c2b.png)

旧版：
![图片](https://user-images.githubusercontent.com/94267417/175866161-a7f58570-a627-47e9-9250-7d6fb3d92034.png)

## 请选择完成以下信息
浏览器：Firefox 101.0.1（64位）
系统：Windows 10 家庭版 64位 21H2
设备：dell 灵越 15-5557

## 其他内容
很长时间之前就有此问题
在同一设备、同一网络下，使用Edge访问则正常

**Comment by Dianliang233** [comment]
无法复现。正在研究 Sentry 数据。

**Comment by Dianliang233** [comment]
Sentry 无记录。请你打开F12查看是否有错误信息。

**Comment by RainStar7981** [comment]
是我这里的问题，关闭adguard插件之后正常了

**Comment by Dianliang233** [comment]
请问你开启了什么规则集？

**Comment by RainStar7981** [comment]
默认

**Comment by RainStar7981** [comment]
![图片](https://user-images.githubusercontent.com/94267417/175870047-ec9f3192-dc89-422d-bda9-c73c906067c3.png)
过滤日志

**Comment by RainStar7981** [comment]
![图片](https://user-images.githubusercontent.com/94267417/175870210-b4ba0453-bd03-4ab9-9a4d-f87bf7c4e1b3.png)
过滤日志

**Comment by Dianliang233** [comment]
![image](https://user-images.githubusercontent.com/45287180/175870132-4dcda3eb-53af-4979-944a-f119b53e58b9.png)

原因：由于删除了了 referer 请求头，请求被 CDN 按照规则没有返回 CORS 头。

也许还是得放到同一个域名。
